name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar

      - name: Build Docker image
        run: docker build -t your-docker-repo/your-app:${{ github.sha }} .

      - name: Push Docker image
        run: docker push your-docker-repo/your-app:${{ github.sha }}

      - name: Deploy to Kubernetes
        uses: actions/kubernetes-action@v1.0.0
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          manifests: |
            k8s/deployment.yaml
            k8s/service.yaml
